### ISSUE TITLE
Potential Hubs and Supernodes are not shown in MeshDB's map

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#489]
So whoops, in a similar vein to #402 we are unable to represent potential hubs and supernodes without assigning an NN. This is obviously bad, since we can't show the correct potential dots on the map for these sites

**Comment by Andrew-Dickinson** [comment]
Options:
1 ) Go back to parsing the word `hub` that we imported from the spreadsheet from the install notes in order to tell the map that this install is a potential hub. Upsides: easy and fast. Downsides: brittle and unpredictable
2) Introduce a new field on install which allows us to select "node type" similar to how we do this with Nodes. Upsides: unambiguous. Downsides: duplicative of the field on node, going to be unused for active nodes
3) Assign NNs for potential hubs? Upsides: simple, few code changes. Downsides: inefficient use of NN allocations
4) Change the primary key for the node object to something other than NN, allowing potential Node objects without assigning an NN. Upsides: no data duplication. Downsides: APIs and URLs get very confusing
4a) Assign potential hubs super high "fake" NNs like `100000xxxx`

**Comment by Andrew-Dickinson** [comment]
Perhaps we could do option 4, but keep all existing URL and API interfaces the same (this might be hella painful in the admin UI though IDK). Basically the only place the real `pk` would be used would be internal to the db, but the URLs would all reference the network number

**Comment by WillNilges** [comment]
After a phonecall, we had two thoughts:
- Add two fields to the Install: "Planned Hub" and "Planned Supernode" which will control the size and color of the dot
- Add a union field between name and NN, where the name field is for when you don't have an NN, but if you assign it, it gets clobbered.

But, the better thing to do would be to update our models so that we don't care about our PK. We turn it into a UUID or something, and then we gain a ton of freedom. @Andrew-Dickinson is going to try doing this.

**Comment by WillNilges** [comment]
https://pypi.org/project/shortuuid/

**Comment by Andrew-Dickinson** [comment]
Jk lol. They're in the DB but they're still not on the map. Should be a pretty easy map tweak to get them to show up

**Comment by Andrew-Dickinson** [comment]
Fixed via #571
