### ISSUE TITLE
Create documentation for how to use meshdb

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#71]
probably important to ease the learning curve as much as possible for people. This will be a totally new web UI for them, hopefully it's as simple and intuitive as possible, but some basic stuff like "how do I create a node number?" or "how do I do XYZ moderately complex thing through the admin UI?" or "what's the difference between an admin and an install leader?" or "how do I connect this to other services?" might be pertinent.

**Comment by LydonThorpe** [comment]
Where do you want this documentation to live? Wiki?

**Comment by Andrew-Dickinson** [comment]
We might end up hosting the docs for this on the site itself, just because that lets us do things like dynamically generate docs based on code content (javadoc style), it also lets you require doc changes in PRs that change the code, etc. However we can always link this content from the wiki, and certainly we should have some basic information over there

**Comment by WillNilges** [comment]
TODO: Add help text on each of our fields.

**Comment by WillNilges** [comment]
Looks like the API docs are live: https://db.grandsvc.mesh.nycmesh.net/api-docs/swagger/#/
and no longer loading infinitely.

Need to remove nonsense [api](https://db.grandsvc.mesh.nycmesh.net/api-docs/swagger/#/api) tab and add [Legacy Query Form](https://db.grandsvc.mesh.nycmesh.net/api-docs/swagger/#/Legacy%20Query%20Form)

**Comment by Andrew-Dickinson** [comment]
Added a bunch of "helpdesk" style articles to the wiki: https://wiki.mesh.nycmesh.net/books/6-services-software/chapter/meshdb

I think this issue is good to resolve. We can supplement with additional information as we encounter gaps
